fix owner of /var/www/matomo/vendor/tecnickcom/tcpdf/fonts
crazy-max/docker-matomo pull request #144
Opened 2023-11-23 08:43 UTC by fritterhoff

Fixes #143

2023-11-25 21:34 UTC, crazy-max commented
Thanks but I think it would be better to add it to https://github.com/crazy-max/docker-matomo/blob/186f7f46be42331b5128b75ac21419b0518641b6/rootfs/etc/cont-init.d/02-fix-perms.sh#L27

2023-11-25 21:34 UTC, crazy-max requested changes
Thanks but I think it would be better to add it to https://github.com/crazy-max/docker-matomo/blob/186f7f46be42331b5128b75ac21419b0518641b6/rootfs/etc/cont-init.d/02-fix-perms.sh#L27

2023-11-26 07:35 UTC, fritterhoff commented
From my point of view, changing the folder permissions it self should be fine (without `-R`). I've changed the location :)

2023-11-26 11:20 UTC, crazy-max requested changes
One nit and also squash your commits please, thanks!

2023-11-26 11:20 UTC, crazy-max commented on rootfs/etc/cont-init.d/02-fix-perms.sh
> +  /var/www/matomo/js
Remove extra space here

2023-11-26 11:24 UTC, fritterhoff commented on rootfs/etc/cont-init.d/02-fix-perms.sh
> +  /var/www/matomo/js
Done :)

2023-11-26 11:56 UTC, crazy-max approved these changes
Thanks

2023-11-26 12:11 UTC, merged